apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-sre-web
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/timmy304681/argocd-app-config.git
    targetRevision: main
    path: prod
  destination: 
    server: https://kubernetes.default.svc
    namespace: prod-sre-web

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true