name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      
    - uses: azure/k8s-lint@v1
      with:
        manifests: |
            dev/deployment.yaml
            dev/service.yaml
            prod/deployment.yaml
            prod/service.yaml
        kubeconformOpts: -summary
                  
    