name: CI/CD Pipeline

on:
  push:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      
    - uses: azure/k8s-lint@v1
      id: k8s-lint
      with:
        manifests: |
            dev/deployment.yaml
            dev/service.yaml
            prod/deployment.yaml
            prod/service.yaml
        kubeconformOpts: -summary


    - uses: actions/github-script@v6
      if: github.event_name == 'pull_request'
      env:
        LINT: "${{ steps.k8s-lint.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `\`${{ steps.fmt.outcome }}\`

          #### `${{ steps.k8s-lint.outcome }}\`
          \`\`\`\n
          ${process.env.LINT}
          \`\`\`


          </details>
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
                      
        